# Generated by Django 3.2.3 on 2021-06-03 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('description', models.TextField(default='', max_length=300, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('icon', models.ImageField(default='', null=True, upload_to='icons/%Y/%m/%d')),
                ('url', models.URLField()),
            ],
        ),
    ]
